### PR TITLE
Remove manual cache clearing UI

### PR DESCRIPTION
**Pull request by wimleers**
Reasons to do this:
1. Purging by path manually is _brittle_, the whole point of Drupal 8 is that we don't need this anymore!
2. "Clear entire cache" is also broken, because it clears "the entire zone", which means _all_ sites in a domain apparently. A CloudFlare account is associated with a domain (in my case `wimleers.com`), but is not necessarily used for the main domain, and can be used for multiple subsites (in my case `dev.wimleers.com`). The CloudFlare module indicates it is associated with `wimleers.com`, and is going to invalidate everything there, even though I specifically only want `dev.wimleers.com` to be purged.
3. One less tab, less complexity, less to maintain.
4. "Purge all" exists in the CloudFlare UI too.

I think we _do_ want "clear entire cache for the domain that this site runs on" whenever modules are installed for example. But that should not have a UI.

### CODE REVIEW

**Comment by aweingarten** [comment]
@wimleers,
Let's catch up on this.  

1: Having worked with clients I still see a use case for clear by path.  Our best systems and automated clears don't always work and a manual button is sometimes necessary.   One example that I could see:  

A site has a view that displays press releases, but no rules to purge the view when new press releases are published.  Without the rule in place we would need to be able to purge by path.  It's a less than idea situation but happens more that you'd expect.  

That being said I think we can be smart about it.  I think it's worth making the purge by path actually try to lookup the cache tags for that page and then purging those tags.  That should be a more robust compromise.  

2: I could see this being confusing too and might be worth investigating.  I would like to dig into multiple zone/domains.  This should be addressed at that point.

3:  Simpler is better :)

4: I might be able to buy into that.

**Comment by wimleers** [comment]
> A site has a view that displays press releases, but no rules to purge the view when new press releases are published. Without the rule in place we would need to be able to purge by path. It's a less than idea situation but happens more that you'd expect.

This does not make sense.
1. A view that displays press releases, means it's displaying entities. The view itself does caching and relies on cache tag invalidation to be updated.
2. You don't _need_ rules (as in CloudFlare page rules) for this at all, the invalidated tags in Drupal are communicated to CloudFlare, which causes it to invalidate all responses containing those cache tags.

> That being said I think we can be smart about it. I think it's worth making the purge by path actually try to lookup the cache tags for that page and then purging those tags. That should be a more robust compromise.

??!?? :D This completely puzzles me!

How would you even _begin_ to look up the cache tags for a page? There's no way you can do that, except rendering the page and then parsing its header. 

## 

I think you may be misunderstanding how cache tags work? See https://www.drupal.org/developing/api/8/cache/tags.

**Comment by aweingarten** [comment]
Status update I am going to do testing this weekend to probe edge cases here.

**Comment by aweingarten** [comment]
@wimleers  
I did some simple analysis here:
1. Created a new view that lists content
2. Created a piece of content
3. Curl the content:
   `curl -SLIXGET http://eeaweingarten.prod.acquia-sites.com/test`

I get back these cache tags:

```
X-Drupal-Cache-Contexts: languages:language_interface route theme timezone url user.permissions user.roles
X-Drupal-Cache-Tags: block_view config:block.block.bartik_account_menu config:block.block.bartik_breadcrumbs config:block.block.bartik_content config:block.block.bartik_footer config:block.block.bartik_help config:block.block.bartik_local_actions config:block.block.bartik_local_tasks config:block.block.bartik_login config:block.block.bartik_main_menu config:block.block.bartik_messages config:block.block.bartik_powered config:block.block.bartik_search config:block.block.bartik_tools config:block_list config:system.menu.account config:system.menu.footer config:system.menu.main config:system.menu.tools config:system.site config:user.role.anonymous node:6 node_view rendered user:0 user:1 user_view
```
1. Curl the view
   `curl -SLIXGET http://eeaweingarten.prod.acquia-sites.com/content-stuff`
   get back

```
X-Drupal-Cache-Contexts: languages:language_interface route theme timezone url user.permissions user.roles
X-Drupal-Cache-Tags: block_view config:block.block.bartik_account_menu config:block.block.bartik_breadcrumbs config:block.block.bartik_content config:block.block.bartik_footer config:block.block.bartik_help config:block.block.bartik_local_actions config:block.block.bartik_local_tasks config:block.block.bartik_login config:block.block.bartik_main_menu config:block.block.bartik_messages config:block.block.bartik_powered config:block.block.bartik_search config:block.block.bartik_tools config:block_list config:system.menu.account config:system.menu.footer config:system.menu.main config:system.menu.tools config:system.site config:user.role.anonymous node:6 node_view rendered user:0 user:1 user_view
```
1. Naive interpretation time:
   I see a LOT of overlap in the tags.  If I author content I assume that if I create content then all the cache tags for the content are cleared.  Based on this example and understanding I accept that the view  would automatically get purged.  No need for complicated rules.  Cool.  Based on this i think it makes sense to pull the manual purge into a separate sub module that makes it pretty clear that this is a fall-back in case something goes wrong somewhere but should no be needed.  

If my understanding is correct my concern with this behavior is that wouldn't it pretty much purge everything in the site?  I find that hard to believe?  I'm trying to think if this would be a vulnerability during a high-traffic event.  If enough pages got purged during a high-traffic event it could degrade the origin servers

**Comment by aweingarten** [comment]
Replaced by https://github.com/d8-contrib-modules/cloudflare/pull/22

which moves the manual cache clearing functions to a seperate module

**Pull request closed without merging**
